/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ACER
 */
public class ArrayForm extends javax.swing.JFrame {

    /**
     * Creates new form ArrayForm
     */
    public ArrayForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jconadokt = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jtxtnama = new javax.swing.JTextField();
        jtxtalamat = new javax.swing.JTextField();
        jtxtusia = new javax.swing.JTextField();
        jtxtjenis = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(251, 54, 0, 0);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Pemilihan Dokter");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(200, 40, 190, 24);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Dokter Spesialis");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 500, 110, 20);

        jconadokt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jconadokt.setForeground(new java.awt.Color(255, 51, 51));
        jconadokt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Salah Satu --", "Dr. Farras Yassar", "Dr. Anisa Putri", "Dr. Harun Fajar" }));
        jconadokt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jconadoktActionPerformed(evt);
            }
        });
        getContentPane().add(jconadokt);
        jconadokt.setBounds(190, 90, 270, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Pilih Dokter");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 100, 90, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Nama");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 180, 90, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Alamat");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 220, 90, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Usia");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 260, 90, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Jenis Kelamin");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(60, 300, 90, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Golongan Darah");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(60, 340, 110, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Status");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(60, 380, 110, 20);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Kewarganegaraan");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(60, 420, 110, 20);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Waktu Praktek");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(60, 460, 110, 20);

        jtxtnama.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtnama.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(jtxtnama);
        jtxtnama.setBounds(190, 170, 270, 30);

        jtxtalamat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtalamat.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(jtxtalamat);
        jtxtalamat.setBounds(190, 210, 270, 30);

        jtxtusia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtusia.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(jtxtusia);
        jtxtusia.setBounds(190, 250, 270, 30);

        jtxtjenis.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtjenis.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(jtxtjenis);
        jtxtjenis.setBounds(190, 290, 270, 30);

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(jTextField5);
        jTextField5.setBounds(190, 370, 270, 30);

        jTextField7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(jTextField7);
        jTextField7.setBounds(190, 410, 270, 30);

        jTextField8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(jTextField8);
        jTextField8.setBounds(190, 490, 270, 30);

        jTextField9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(jTextField9);
        jTextField9.setBounds(190, 330, 270, 30);

        jTextField10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField10.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(jTextField10);
        jTextField10.setBounds(190, 450, 270, 30);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setForeground(new java.awt.Color(255, 153, 153));
        jPanel1.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Identitas");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 140, 90, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 550, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jconadoktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jconadoktActionPerformed
        // TODO add your handling code here:
        if(jconadokt.getSelectedItem().equals("Dr. Farras Yassar")){
jtxtnama.setText("DR. Farras Yassar ");
jtxtalamat.setText("Jl. Surabaya 16, Malang");
jtxtusia.setText("20 Tahun");
jtxtjenis.setText("Laki-Laki");
jTextField9.setText("A");
jTextField5.setText("Belum Menikah ");
jTextField7.setText("Indonesia");
jTextField10.setText("Dokter Umum");
jTextField8.setText(" Pagi (07.00-15.00)");
}
else
if(jconadokt.getSelectedItem().equals("Dr. Anisa Putri")){
jtxtnama.setText("DR. Anisa Putri");
jtxtalamat.setText("Jl. Veteran 3, Malang");
jtxtusia.setText("20 Tahun");
jtxtjenis.setText("Perempuan");
jTextField9.setText("O");
jTextField5.setText("Belum Menikah");
jTextField7.setText("Indonesia");
jTextField10.setText("Dokter Gigi");
jTextField8.setText(" Sore (16.00-22.00)");
}
else
if(jconadokt.getSelectedItem().equals("Dr. Harun Fajar")){
jtxtnama.setText("DR. Harun Fajar ");
jtxtalamat.setText("Jl. Bandung 9, Malang");
jtxtusia.setText("20 Tahun");
jtxtjenis.setText("Laki-Laki");
jTextField9.setText("B");
jTextField5.setText("Belum Menikah");
jTextField7.setText("Indonesia");
jTextField10.setText("Dokter Gizi");
jTextField8.setText(" Malam (22.00-06.00)");
        }
    }//GEN-LAST:event_jconadoktActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArrayForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArrayForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArrayForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArrayForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArrayForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JComboBox<String> jconadokt;
    private javax.swing.JTextField jtxtalamat;
    private javax.swing.JTextField jtxtjenis;
    private javax.swing.JTextField jtxtnama;
    private javax.swing.JTextField jtxtusia;
    // End of variables declaration//GEN-END:variables
}
