/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ACER
 */
public class Tugas_Praktikum_2 extends javax.swing.JFrame {

    /**
     * Creates new form Tugas_Praktikum_2
     */
    public Tugas_Praktikum_2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jtxtguru1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jcbday = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jtxtmapel1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jtxtmapel2 = new javax.swing.JTextField();
        jtxtguru2 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jtxtmapel3 = new javax.swing.JTextField();
        jtxtguru3 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jtxtmapel4 = new javax.swing.JTextField();
        jtxtguru4 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jtxtguru8 = new javax.swing.JTextField();
        jtxtmapel5 = new javax.swing.JTextField();
        jtxtguru5 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jtxtmapel6 = new javax.swing.JTextField();
        jtxtguru6 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jtxtmapel7 = new javax.swing.JTextField();
        jtxtguru7 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jtxtmapel8 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jtxtmapel9 = new javax.swing.JTextField();
        jtxtguru9 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jtxtmapel10 = new javax.swing.JTextField();
        jtxtguru10 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jtxtmapel11 = new javax.swing.JTextField();
        jtxtguru11 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxtnama = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtxtalamat = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtxtusia = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtxtjenis = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setForeground(new java.awt.Color(255, 153, 153));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(153, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 102), 6));
        jPanel2.setForeground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Mata Pelajaran");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(130, 210, 160, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setText("1");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(60, 250, 40, 30);

        jtxtguru1.setBackground(new java.awt.Color(255, 102, 102));
        jtxtguru1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtguru1.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.add(jtxtguru1);
        jtxtguru1.setBounds(300, 250, 190, 30);

        jLabel2.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("COASTER SCHEDULE");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(150, 40, 320, 40);

        jcbday.setBackground(new java.awt.Color(255, 102, 102));
        jcbday.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcbday.setForeground(new java.awt.Color(255, 51, 102));
        jcbday.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Salah Satu --", "Senin", "Selasa", "Rabu", "Kamis", "Jum'at" }));
        jcbday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbdayActionPerformed(evt);
            }
        });
        jPanel2.add(jcbday);
        jcbday.setBounds(190, 100, 270, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Tentukan Hari");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(60, 110, 120, 20);

        jtxtmapel1.setBackground(new java.awt.Color(255, 153, 153));
        jtxtmapel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtmapel1.setForeground(new java.awt.Color(255, 51, 51));
        jtxtmapel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtmapel1ActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtmapel1);
        jtxtmapel1.setBounds(100, 250, 180, 30);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("Guru Pengajar");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(340, 210, 160, 30);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setText("Jam Pelajaran Ke -");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(220, 180, 160, 20);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel17.setText("2");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(60, 300, 40, 30);

        jtxtmapel2.setBackground(new java.awt.Color(255, 102, 102));
        jtxtmapel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtmapel2.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.add(jtxtmapel2);
        jtxtmapel2.setBounds(100, 300, 180, 30);

        jtxtguru2.setBackground(new java.awt.Color(255, 153, 153));
        jtxtguru2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtguru2.setForeground(new java.awt.Color(255, 153, 153));
        jPanel2.add(jtxtguru2);
        jtxtguru2.setBounds(300, 300, 190, 30);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel18.setText("3");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(60, 350, 40, 30);

        jtxtmapel3.setBackground(new java.awt.Color(255, 153, 153));
        jtxtmapel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtmapel3.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.add(jtxtmapel3);
        jtxtmapel3.setBounds(100, 350, 180, 30);

        jtxtguru3.setBackground(new java.awt.Color(255, 102, 102));
        jtxtguru3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtguru3.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.add(jtxtguru3);
        jtxtguru3.setBounds(300, 350, 190, 30);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel19.setText("4");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(60, 400, 40, 30);

        jtxtmapel4.setBackground(new java.awt.Color(255, 102, 102));
        jtxtmapel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtmapel4.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.add(jtxtmapel4);
        jtxtmapel4.setBounds(100, 400, 180, 30);

        jtxtguru4.setBackground(new java.awt.Color(255, 153, 153));
        jtxtguru4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtguru4.setForeground(new java.awt.Color(255, 153, 153));
        jPanel2.add(jtxtguru4);
        jtxtguru4.setBounds(300, 400, 190, 30);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel20.setText("5");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(60, 450, 40, 30);

        jtxtguru8.setBackground(new java.awt.Color(255, 153, 153));
        jtxtguru8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtguru8.setForeground(new java.awt.Color(255, 153, 153));
        jPanel2.add(jtxtguru8);
        jtxtguru8.setBounds(300, 600, 190, 30);

        jtxtmapel5.setBackground(new java.awt.Color(255, 153, 153));
        jtxtmapel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtmapel5.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.add(jtxtmapel5);
        jtxtmapel5.setBounds(100, 450, 180, 30);

        jtxtguru5.setBackground(new java.awt.Color(255, 102, 102));
        jtxtguru5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtguru5.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.add(jtxtguru5);
        jtxtguru5.setBounds(300, 450, 190, 30);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel21.setText("6");
        jPanel2.add(jLabel21);
        jLabel21.setBounds(60, 500, 40, 30);

        jtxtmapel6.setBackground(new java.awt.Color(255, 102, 102));
        jtxtmapel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtmapel6.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.add(jtxtmapel6);
        jtxtmapel6.setBounds(100, 500, 180, 30);

        jtxtguru6.setBackground(new java.awt.Color(255, 153, 153));
        jtxtguru6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtguru6.setForeground(new java.awt.Color(255, 153, 153));
        jPanel2.add(jtxtguru6);
        jtxtguru6.setBounds(300, 500, 190, 30);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel22.setText("7");
        jPanel2.add(jLabel22);
        jLabel22.setBounds(60, 550, 40, 30);

        jtxtmapel7.setBackground(new java.awt.Color(255, 153, 153));
        jtxtmapel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtmapel7.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.add(jtxtmapel7);
        jtxtmapel7.setBounds(100, 550, 180, 30);

        jtxtguru7.setBackground(new java.awt.Color(255, 102, 102));
        jtxtguru7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtguru7.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.add(jtxtguru7);
        jtxtguru7.setBounds(300, 550, 190, 30);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel23.setText("8");
        jPanel2.add(jLabel23);
        jLabel23.setBounds(60, 600, 40, 30);

        jtxtmapel8.setBackground(new java.awt.Color(255, 102, 102));
        jtxtmapel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtmapel8.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.add(jtxtmapel8);
        jtxtmapel8.setBounds(100, 600, 180, 30);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel24.setText("9");
        jPanel2.add(jLabel24);
        jLabel24.setBounds(60, 650, 40, 30);

        jtxtmapel9.setBackground(new java.awt.Color(255, 153, 153));
        jtxtmapel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtmapel9.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.add(jtxtmapel9);
        jtxtmapel9.setBounds(100, 650, 180, 30);

        jtxtguru9.setBackground(new java.awt.Color(255, 102, 102));
        jtxtguru9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtguru9.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.add(jtxtguru9);
        jtxtguru9.setBounds(300, 650, 190, 30);

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel25.setText("10");
        jPanel2.add(jLabel25);
        jLabel25.setBounds(60, 700, 40, 30);

        jtxtmapel10.setBackground(new java.awt.Color(255, 102, 102));
        jtxtmapel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtmapel10.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.add(jtxtmapel10);
        jtxtmapel10.setBounds(100, 700, 180, 30);

        jtxtguru10.setBackground(new java.awt.Color(255, 153, 153));
        jtxtguru10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtguru10.setForeground(new java.awt.Color(255, 153, 153));
        jPanel2.add(jtxtguru10);
        jtxtguru10.setBounds(300, 700, 190, 30);

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel26.setText("11");
        jPanel2.add(jLabel26);
        jLabel26.setBounds(60, 750, 40, 30);

        jtxtmapel11.setBackground(new java.awt.Color(255, 153, 153));
        jtxtmapel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtmapel11.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.add(jtxtmapel11);
        jtxtmapel11.setBounds(100, 750, 180, 30);

        jtxtguru11.setBackground(new java.awt.Color(255, 102, 102));
        jtxtguru11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtguru11.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.add(jtxtguru11);
        jtxtguru11.setBounds(300, 750, 190, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 550, 650);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Nama");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(60, 180, 90, 20);

        jtxtnama.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtnama.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(jtxtnama);
        jtxtnama.setBounds(190, 170, 270, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Alamat");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(60, 220, 90, 20);

        jtxtalamat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtalamat.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(jtxtalamat);
        jtxtalamat.setBounds(190, 210, 270, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Usia");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(60, 260, 90, 20);

        jtxtusia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtusia.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(jtxtusia);
        jtxtusia.setBounds(190, 250, 270, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Jenis Kelamin");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(60, 300, 90, 20);

        jtxtjenis.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtjenis.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(jtxtjenis);
        jtxtjenis.setBounds(190, 290, 270, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Golongan Darah");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(60, 340, 110, 20);

        jTextField9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(jTextField9);
        jTextField9.setBounds(190, 330, 270, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Status");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(60, 380, 110, 20);

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(jTextField5);
        jTextField5.setBounds(190, 370, 270, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Kewarganegaraan");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(60, 420, 110, 20);

        jTextField7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(jTextField7);
        jTextField7.setBounds(190, 410, 270, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Waktu Praktek");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(60, 460, 110, 20);

        jTextField10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField10.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(jTextField10);
        jTextField10.setBounds(190, 450, 270, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Dokter Spesialis");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 500, 110, 20);

        jTextField8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(jTextField8);
        jTextField8.setBounds(190, 490, 270, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbdayActionPerformed
        // TODO add your handling code here:
        if(jcbday.getSelectedItem().equals("Senin")){
            jtxtmapel1.setText("UPACARA");
            jtxtguru1.setText("Pembina");
            jtxtmapel2.setText("PKN");
            jtxtguru2.setText("FAJAR SETIYAWAN, S.Pd");
            jtxtmapel3.setText("PKN");
            jtxtguru3.setText("FAJAR SETIYAWAN, S.Pd");
            jtxtmapel4.setText("MATEMATIKA");
            jtxtguru4.setText("TULUS ANDRIANTO, S.Pd");
            jtxtmapel5.setText("MATEMATIKA");
            jtxtguru5.setText("TULUS ANDRIANTO, S.Pd");
            jtxtmapel6.setText("BK");
            jtxtguru6.setText("PENI WARDAYANAI, S.Pd");
            jtxtmapel7.setText("BIN");
            jtxtguru7.setText("FELLY FITRIANI SUPRIYADI, S.Pd");
            jtxtmapel8.setText("BIN");
            jtxtguru8.setText("FELLY FITRIANI SUPRIYADI, S.Pd");
            jtxtmapel9.setText("FISIKA");
            jtxtguru9.setText("Mr. JIMMY");
            jtxtmapel10.setText("FISIKA");
            jtxtguru10.setText("Mr. JIMMY");
            jtxtmapel11.setText("FISIKA");
            jtxtguru11.setText("Mr. JIMMY");
            
        }
        else
        if(jcbday.getSelectedItem().equals("Selasa")){
            jtxtmapel1.setText("RBJ");
            jtxtguru1.setText("HIRGA ERTAMA PUTRA, S.Kom");
            jtxtmapel2.setText("RBJ");
            jtxtguru2.setText("HIRGA ERTAMA PUTRA, S.Kom");
            jtxtmapel3.setText("RBJ");
            jtxtguru3.setText("HIRGA ERTAMA PUTRA, S.Kom");
            jtxtmapel4.setText("SISTEL");
            jtxtguru4.setText("Mr. LARSO");
            jtxtmapel5.setText("SISTEL");
            jtxtguru5.setText("Mr. LARSO");
            jtxtmapel6.setText("ADSER");
            jtxtguru6.setText("SUSANTO, S.Kom");
            jtxtmapel7.setText("ADSER");
            jtxtguru7.setText("SUSANTO, S.Kom");
            jtxtmapel8.setText("ADSER");
            jtxtguru8.setText("SUSANTO, S.Kom");
            jtxtmapel9.setText("PPB");
            jtxtguru9.setText("HENDRA WAHYU PRASETYA");
            jtxtmapel10.setText("PPB");
            jtxtguru10.setText("HENDRA WAHYU PRASETYA");
            jtxtmapel11.setText("PPB");
            jtxtguru11.setText("HENDRA WAHYU PRASETYA");
            
        }
        else
        if(jcbday.getSelectedItem().equals("Rabu")){
            jtxtmapel1.setText("DESKTOP");
            jtxtguru1.setText("HENDRO SOEMARNO, S.T");
            jtxtmapel2.setText("DESKTOP");
            jtxtguru2.setText("HENDRO SOEMARNO, S.T");
            jtxtmapel3.setText("PAI");
            jtxtguru3.setText("AHMAD NASIKIN, S.Pd");
            jtxtmapel4.setText("PAI");
            jtxtguru4.setText("AHMAD NASIKIN, S.Pd");
            jtxtmapel5.setText("BIN");
            jtxtguru5.setText("FELLY FITRIANI SUPRIYADI, S.Pd");
            jtxtmapel6.setText("BIG");
            jtxtguru6.setText("LARASATI KHOIRUN NISA, S.Pd");
            jtxtmapel7.setText("BIG");
            jtxtguru7.setText("LARASATI KHOIRUN NISA, S.Pd");
            jtxtmapel8.setText("PKWU");
            jtxtguru8.setText("TITIK APRIANAN DEWI, S.Pd");
            jtxtmapel9.setText("PKWU");
            jtxtguru9.setText("TITIK APRIANAN DEWI, S.Pd");
            jtxtmapel10.setText("SEJIN");
            jtxtguru10.setText("Mr. ANDI, S.Pd");
            jtxtmapel11.setText("SEJIN");
            jtxtguru11.setText("Mr. ANDI, S.Pd");
           
        }
         else
        if(jcbday.getSelectedItem().equals("Kamis")){
            jtxtmapel1.setText("DESKTOP");
            jtxtguru1.setText("HENDRO SOEMARNO, S.T");
            jtxtmapel2.setText("DESKTOP");
            jtxtguru2.setText("HENDRO SOEMARNO, S.T");
            jtxtmapel3.setText("B.JAWA");
            jtxtguru3.setText("SRI CHUSNUL HANIYAH,S.Pd");
            jtxtmapel4.setText("B.JAWA");
            jtxtguru4.setText("SRI CHUSNUL HANIYAH,S.Pd");
            jtxtmapel5.setText("SENBUD");
            jtxtguru5.setText("FIRMANSYAH AYATULLAH, S.Kom");
            jtxtmapel6.setText("SENBUD");
            jtxtguru6.setText("FIRMANSYAH AYATULLAH, S.Kom");
            jtxtmapel7.setText("PWD");
            jtxtguru7.setText("FIRDAUSA S.Pd");
            jtxtmapel8.setText("PWD");
            jtxtguru8.setText("FIRDAUSA S.Pd");
            jtxtmapel9.setText("PWD");
            jtxtguru9.setText("FIRDAUSA S.Pd");
            jtxtmapel10.setText("PPL");
            jtxtguru10.setText("IFA CHOIRUNNISA, S.Pd");
            jtxtmapel11.setText("PPL");
            jtxtguru11.setText("IFA CHOIRUNNISA, S.Pd");
        }
         else
        if(jcbday.getSelectedItem().equals("Jum'at")){
            jtxtmapel1.setText("PEMBIASAAN");
            jtxtguru1.setText("");
            jtxtmapel2.setText("OR");
            jtxtguru2.setText("Mr. THORIQ");
            jtxtmapel3.setText("OR");
            jtxtguru3.setText("Mr. THORIQ");
            jtxtmapel4.setText("PAI");
            jtxtguru4.setText("AHMAD NASIKIN, S.Pd");
            jtxtmapel5.setText("PBO");
            jtxtguru5.setText("MUHAMMAD ARIFIN, S.Kom");
            jtxtmapel6.setText("PBO");
            jtxtguru6.setText("MUHAMMAD ARIFIN, S.Kom");
            jtxtmapel7.setText("PBO");
            jtxtguru7.setText("MUHAMMAD ARIFIN, S.Kom");
            jtxtmapel8.setText("BASDAT");
            jtxtguru8.setText("IFA CHOIRUNNISA, S.Pd");
            jtxtmapel9.setText("BASDAT");
            jtxtguru9.setText("IFA CHOIRUNNISA, S.Pd");
            jtxtmapel10.setText("BASDAT");
            jtxtguru10.setText("IFA CHOIRUNNISA, S.Pd");
            
        }
    }//GEN-LAST:event_jcbdayActionPerformed

    private void jtxtmapel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtmapel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtmapel1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tugas_Praktikum_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tugas_Praktikum_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tugas_Praktikum_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tugas_Praktikum_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tugas_Praktikum_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JComboBox<String> jcbday;
    private javax.swing.JTextField jtxtalamat;
    private javax.swing.JTextField jtxtguru1;
    private javax.swing.JTextField jtxtguru10;
    private javax.swing.JTextField jtxtguru11;
    private javax.swing.JTextField jtxtguru2;
    private javax.swing.JTextField jtxtguru3;
    private javax.swing.JTextField jtxtguru4;
    private javax.swing.JTextField jtxtguru5;
    private javax.swing.JTextField jtxtguru6;
    private javax.swing.JTextField jtxtguru7;
    private javax.swing.JTextField jtxtguru8;
    private javax.swing.JTextField jtxtguru9;
    private javax.swing.JTextField jtxtjenis;
    private javax.swing.JTextField jtxtmapel1;
    private javax.swing.JTextField jtxtmapel10;
    private javax.swing.JTextField jtxtmapel11;
    private javax.swing.JTextField jtxtmapel2;
    private javax.swing.JTextField jtxtmapel3;
    private javax.swing.JTextField jtxtmapel4;
    private javax.swing.JTextField jtxtmapel5;
    private javax.swing.JTextField jtxtmapel6;
    private javax.swing.JTextField jtxtmapel7;
    private javax.swing.JTextField jtxtmapel8;
    private javax.swing.JTextField jtxtmapel9;
    private javax.swing.JTextField jtxtnama;
    private javax.swing.JTextField jtxtusia;
    // End of variables declaration//GEN-END:variables
}
